apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: second-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.10.240-192.168.10.249
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example2
  namespace: metallb-system
spec:
  ipAddressPools:
  - second-pool
