apiVersion: v1
kind: Service
metadata:
  name: echo-pods-argo
spec:
#   type: ClusterIP
  type: NodePort
#   type: LoadBalancer
#   loadBalancerIP: 192.168.10.242
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 80
  selector:
    app: echo-pods-argo
