apiVersion: v1
kind: Service
metadata:
  name: echo-pods-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30080
  selector:
    app: echo-pods
