apiVersion: v1
kind: Service
metadata:
  name: echo-pods-np
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: echo-pods
