apiVersion: v1
kind: Service
metadata:
  name: echo-pods
  labels:
    app: echo-pods
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: echo-pods
