apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-pods
  labels:
    app: echo-pods
spec:
  replicas: 4
  selector:
    matchLabels:
      app: echo-pods
  template:
    metadata:
      labels:
        app: echo-pods
    spec:
      containers:
      - name: echo-pods
        image: muruu1/echo-pods:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: echo-pods-svc
  labels:
    app: echo-pods
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: echo-pods