apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-pods-dep
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 4
  selector:
    matchLabels:
      app: echo-pods
  template:
    metadata:
      labels:
        app: echo-pods
    spec:
      containers:
        - name: echo-pods
          image: muruu1/echo-pods:v1.0
          imagePullPolicy: Always
