apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: echo-pods-rs
spec:
  replicas: 4
  selector:
    matchLabels:
      app: echo-pods
  template:
    metadata:
      labels:
        app: echo-pods
    spec:
      containers:
        - name: echo-pods
          image: muruu1/echo-pods:v1.0
          imagePullPolicy: Always
