name: Custom Image Build and Release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  URL_TO_OS_IMAGE: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
  IMAGE_FILE: ubuntu-custom-cloudimg.img

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Download OS Image
        run: |
          curl -o $IMAGE_FILE $URL_TO_OS_IMAGE

      - name: Install libguestfs-tools
        run: |
          sudo apt-get update
          sudo apt-get install -y libguestfs-tools

      - name: Customize Image
        run: |
          sudo virt-customize \
            -a $IMAGE_FILE \
            --install qemu-guest-agent \
            --timezone Asia/Tokyo \
            --edit '/etc/ssh/sshd_config:s/PasswordAuthentication no/PasswordAuthentication yes/'

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     draft: false
      #     prerelease: false

      - name: Upload Artifact to Release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: $IMAGE_FILE
          asset_name: $IMAGE_FILE
