name: test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  URL_TO_OS_IMAGE: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
  IMAGE_FILE: ubuntu-custom-cloudimg.img

jobs:
  customize_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Ubuntu Cloud Image
        run: |
          curl -o $IMAGE_FILE $URL_TO_OS_IMAGE

      - name: Install libguestfs-tools
        run: |
          sudo apt-get update
          sudo apt-get install -y libguestfs-tools

      - name: Customize Image
        run: |
          sudo virt-customize \
            -a $IMAGE_FILE \
            --install qemu-guest-agent \
            --timezone Asia/Tokyo \
            --edit '/etc/ssh/sshd_config:s/PasswordAuthentication no/PasswordAuthentication yes/'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Customized Ubuntu Image v1.0.0
          draft: false
          prerelease: false

      - name: Upload Image to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: $IMAGE_FILE
          asset_name: $IMAGE_FILE
          asset_content_type: application/octet-stream
